### ISSUE TITLE
Shipping details not uploading

### ISSUE THREAD

**Issue by karthik-mobo** [augustusnaz/laravel-google-merchant-api#12]
Hi, 

I have inserted basic products details to google merchant using content api, It was fine.

When trying with ->shipping(), its not updating the shipping details. Can you please give any example to upload shipping and taxes in content api.

Thanks

**Comment by alibaba258** [comment]
Same problem here using Package 1.0.4 and Laravel 8

**Comment by mohamedhussieen** [comment]
@karthik-mobo  how you insert product 
may u help me ! 
all apis return respone 500 
list , get and insert

**Comment by karthik-mobo** [comment]
@mohamedhussieen I was used the below to upload the data, but as I need some more options to push to google merchant so I have moved to the xml feed to upload product data.

$merchant_api = new MerchantApi();
$response = $merchant_api->insert($product_array);

*$product_array - Custom array with product data

**Comment by soowa** [comment]
Came here because I encountered the same issue, however i found the following code to work,

`->shipping(['country' => 'BE', 'price' => [
                        'value' => 5,
                        'currency' => 'EUR']
                    ])`
