### ISSUE TITLE
Multiple Account Support

### ISSUE THREAD

**Issue by torro-uk** [augustusnaz/laravel-google-merchant-api#3]
Hi,

I am using your library to push content into our GMC account but we need to be able to support different accounts through the same Laravel instance - using Queues. Is this possible? I tried to overwrite the runtime config which works locally but when running in production it doesn't seem to work. Can config values be passed into the library rather than always pulling from config variables?

**Comment by augustusnaz** [comment]
Hi mate,

Just seen this and also ur PR. Great feature. I'm currently working on an
enterprise app with multiple merchants so this feature would benefit me too.

Might have to sit back and come up with a good architecture. Was ur PR sent
to solve this problem? What I can think of right now is having a
merchant() method
that can be piped with the other methods like  insert() to switch between
merchants.

Will read through ur PR and see what u did.

Augustus

**Comment by torro-uk** [comment]
Hi. I'll be honest, the PR is pretty rough and ready and was just a quick method of supporting multiple merchant configurations. I more API led route would likely be better. I needed this feature quickly so the solution isn't the most elegant but does work.

**Comment by augustusnaz** [comment]
I've gone tahead and made changes which now includes a merchant() method
that takes a string (name of a pre-defined merchant in the config) or an
array (inline merchant config). The method sets app_name, merchant_id, and
client_credentials_path and inits a new client.

Also updated readme and config. Branched multi-merchant
<http:///augustusnaz/laravel-google-merchant-api/tree/multi-merchant> with
changes.
If u dont mind u could look through and run tests urself. Otherwise it'll
take me a while before merging it into master .

**Comment by torro-uk** [comment]
That's super quick work! I have pulled the "multi-merchant" branch into my app and tested the `merchant` function by passing in (as an array) the configurations I had and it correctly connected to each GMC account and updated the product as expected! Looks good to me! Thanks for updating to support the feature!

**Comment by torro-uk** [comment]
Hey. I have found a potential issue with the new multi-merchant functionality. When testing using `queue:work` it successfully connects to the different MC accounts but when running through a Supervisor Redis Queue on Laravel Forge it fails with a "login required". Using a `queue:work` on forge works too so it must be something to do with the runtime compiled nature. Not sure if anything can be done?

**Comment by augustusnaz** [comment]
Oh no! What operation is ur `queue:work` calling? The Oder API scout? If not I suspect it's not an issue with the package.

**Comment by torro-uk** [comment]
Hey!

So, for each product i want to publish to GMC I create a Laravel Job (using Redis). The Job then runs the following (simplified) code:

```
use MOIREI\GoogleMerchantApi\Api\ProductApi;
use MOIREI\GoogleMerchantApi\Contents\Product\Product as GMProduct;

$gmProduct = (new GMProduct)->with($item);
ProductApi::merchant($configArray1)->insert($gmProduct);
ProductApi::merchant($configArray2)->insert($gmProduct);
```

When manually starting the `queue:work` command from Homestead CLI, it correctly switches between the merchant accounts and pushes the product to each GMC as expected. The same seems to work when manually running the command on a Laravel Forge managed server.

If I then create a Queue worker in the Forge Admin (as below) I then get "Login Required" error responses, as if the credentials weren't being updated - despite it trying to POST to the correct merchantID.

<img width="1041" alt="Screenshot 2020-07-22 at 09 01 42" src="https://user-images.githubusercontent.com/68008600/88151016-0b4bc900-cbfa-11ea-969e-321412ba9e45.png">

Not sure if this is related to the merchant function, or the way the queue is setup on forge. Any help would be appreciated!

**Comment by augustusnaz** [comment]
I don't think it's an issue with the package.

Check the credentials file permissions again the worker runtime user. Since the switch has the correct merchant ID and file path and the only difference is the user.
