### ISSUE TITLE
Composer install error

### ISSUE THREAD

**Issue by robertolacav** [augustusnaz/laravel-google-merchant-api#8]
I am trying to install but it is giving me this error when I enter the command 
> composer require moirei/laravel-google-merchant-api

MOIREI\GoogleMerchantApi: Could not determine merchant credentials.

Might you help me?

Thanks!!

**Comment by robertolacav** [comment]
?

**Comment by vicenteibermedia** [comment]
Did anyone solve this?

**Comment by majidalimughal** [comment]
vendor/moirei/laravel-google-merchant-api/src/api/Abstract.php

in this File commenting out the $this->merchant($config);
and hit composer dump-autoload worked for me
